services:
  nim-llm:
    container_name: nim-llm-ms
    image: nvcr.io/nim/nv-mistralai/mistral-nemo-12b-instruct:1.8.0-rtx
    volumes:
    - ${MODEL_DIRECTORY:-./}:/opt/nim/.cache
    user: "${UID}:${GID}"
    ports:
    - "8999:8000"
    expose:
    - "8000"
    environment:
      NGC_API_KEY: ${NGC_API_KEY}
      NIM_RELAX_MEM_CONSTRAINTS: 1
    shm_size: 8gb
    devices:
      - nvidia.com/gpu=all
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000/v1/health/ready')"]
      interval: 10s
      timeout: 20s
      retries: 100
    profiles: ["", "rag"]

  nemoretriever-embedding-ms:
    container_name: nemoretriever-embedding-ms
    image: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.5.0
    volumes:
    - ${MODEL_DIRECTORY:-./}:/opt/nim/.cache
    ports:
    - "9080:8000"
    # expose:
    # - "8000"
    environment:
      NGC_API_KEY: ${NGC_API_KEY}
      NIM_NUM_TOKENIZERS: 1
    user: "${UID}:${GID}"
    shm_size: 16GB
    devices:
      - nvidia.com/gpu=all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10m
    profiles: ["", "rag", "ingest"]

  nemoretriever-ranking-ms:
    container_name: nemoretriever-ranking-ms
    image: nvcr.io/nim/nvidia/llama-3.2-nv-rerankqa-1b-v2:latest
    volumes:
    - ${MODEL_DIRECTORY:-./}:/opt/nim/.cache
    ports:
    - "1976:8000"
    expose:
    - "8000"
    environment:
      NGC_API_KEY: ${NGC_API_KEY}
      NIM_NUM_TOKENIZERS: 1
    user: "${UID}:${GID}"
    devices:
      - nvidia.com/gpu=all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health/ready"]
      interval: 10s
      timeout: 20s
      retries: 100
    profiles: ["", "rag"]

  page-elements:
    image: nvcr.io/nvstaging/nim/nemoretriever-page-elements-v2:1.3.1-rc1-latest-datacenter-release-29610547
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    user: root
    environment:
      - NIM_HTTP_API_PORT=8000
      - NIM_TRITON_LOG_VERBOSE=1
      - NGC_API_KEY=${NGC_API_KEY:-nvidiaapikey}
      - CUDA_VISIBLE_DEVICES=0
      - NIM_TRITON_MODEL_BATCH_SIZE=${PAGE_ELEMENTS_BATCH_SIZE:-1}
      # NIM OpenTelemetry Settings
      - NIM_OTEL_SERVICE_NAME=page-elements
      - NIM_OTEL_TRACES_EXPORTER=otlp
      - NIM_OTEL_METRICS_EXPORTER=console
      - NIM_OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - NIM_ENABLE_OTEL=true
      # Triton OpenTelemetry Settings
      - TRITON_OTEL_URL=http://otel-collector:4318/v1/traces
      - TRITON_OTEL_RATE=1
    devices:
      - nvidia.com/gpu=all
    profiles: ["", "ingest"]

  graphic-elements:
    image: nvcr.io/nvstaging/nim/nemoretriever-graphic-elements-v1:1.3.1-rc1-latest-datacenter-release-29610548
    ports:
      - "8003:8000"
      - "8004:8001"
      - "8005:8002"
    user: root
    environment:
      - NIM_HTTP_API_PORT=8000
      - NIM_TRITON_LOG_VERBOSE=1
      - NVIDIA_API_KEY=${NGC_API_KEY:-nvidiaapikey}
      - NGC_API_KEY=${NGC_API_KEY:-nvidiaapikey}
      - CUDA_VISIBLE_DEVICES=0
      - NIM_TRITON_MODEL_BATCH_SIZE=${GRAPHIC_ELEMENTS_BATCH_SIZE:-1}
    devices:
      - nvidia.com/gpu=all
    profiles: ["", "ingest"]

  table-structure:
    image: nvcr.io/nvstaging/nim/nemoretriever-table-structure-v1:1.3.1-rc1-latest-datacenter-release-29610549
    ports:
      - "8006:8000"
      - "8007:8001"
      - "8008:8002"
    user: root
    environment:
      - NIM_HTTP_API_PORT=8000
      - NIM_TRITON_LOG_VERBOSE=1
      - NGC_API_KEY=${NGC_API_KEY:-nvidiaapikey}
      - CUDA_VISIBLE_DEVICES=0
      - NIM_TRITON_MODEL_BATCH_SIZE=${TABLE_STRUCTURE_BATCH_SIZE:-1}
    devices:
      - nvidia.com/gpu=all
    profiles: ["", "ingest"]

  paddle:
    image: nvcr.io/nim/baidu/paddleocr:1.1.0-rtx
    shm_size: 2gb
    ports:
      - "8009:8000"
      - "8010:8001"
      - "8011:8002"
    user: root
    environment:
      - NIM_HTTP_API_PORT=8000
      - NIM_TRITON_LOG_VERBOSE=1
      - NGC_API_KEY=${NGC_API_KEY:-nvidiaapikey}
      - CUDA_VISIBLE_DEVICES=0
    devices:
      - nvidia.com/gpu=all
    profiles: ["", "ingest"]

networks:
  default:
    name: nvidia-rag
